baseurl: ""

theme: minima
title: CFornesa
author: Chris Fornesa
description: A portfolio of data work by Chris Fornesa.

header_pages:
  - index.md
  - about.md
  - portfolio.md

links:
  - title: "Coded Art"
    url: "https://art.cfornesa.com"
