baseurl: ""

# Basic Information

title: CFornesa
author: Chris Fornesa
email: cfornesa@bu.edu
description: A portfolio of data work by Chris Fornesa.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/cfornesa" }
    - { platform: devto,          user_url: "https://dev.to/cfornesa" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/cfornesa" }

# Header Pages
header_pages:
  - index.md
  - about.md
  - portfolio.md

# Footer Social Links
github_username:  cfornesa
linkedin_username: cfornesa
devto_username:  cfornesa

# Build settings
markdown: kramdown
theme: minima
