baseurl: ""

remote_theme: pages-themes/modernist@v0.2.0
title: CFornesa
author: Chris Fornesa
description: A portfolio of data work by Chris Fornesa.

header_pages:
  - about.md
  - portfolio.md

links:
  - title: "Coded Art"
    url: "https://art.cfornesa.com"
