baseurl: ""

# Basic Information

title: CFornesa
author: Chris Fornesa
email: cfornesa@bu.edu
description: A portfolio of data work by Chris Fornesa.

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/cfornesa" }
    - { platform: twitter, user_url: "https://twitter.com/cfornesa" }

# Header Pages
header_pages:
  - index.md
  - about.md
  - portfolio.md

# Footer Social Links
github_username:  cfornesa
linkedin_username: cfornesa
devto_username:  cfornesa

# Build settings
markdown: kramdown
theme: minima
